// frontend/src/components/RouteMap/index.svelte
<script lang="ts">
  import Spinner from "../Spinner.svelte";
  import { onMount, onDestroy } from "svelte";
  import { setDefaultOptions, loadModules } from "esri-loader";
  import type { Airport, Route } from "../MainPanel/RouteInfo/types";
  import { ThemeKind, curTheme } from "../../settings/theme";
  import { AirportRunways } from "./runways";
  import type Map from "esri/Map";
  import type Basemap from "esri/Basemap";
  import type { Point, Polyline } from "esri/geometry";
  import type {
    SimpleLineSymbol,
    SimpleMarkerSymbol,
    TextSymbol,
  } from "esri/symbols";

  export let selectedRoute: Route | undefined = undefined;

  let mapContainer: any = undefined;

  let map: Map;
  let view: any;
  let airportRunways: AirportRunways;

  let drawingRoute = false;

  let textColor: string;
  let basemap: string;

  $: updateTheme($curTheme);
  $: drawRouteAndRunways(selectedRoute).catch((err) => console.error(err));

  async function updateTheme(theme: ThemeKind) {
    switch (theme) {
      case ThemeKind.Dark:
        textColor = "white";
        basemap = "dark-gray-vector";
        break;
      case ThemeKind.Light:
        textColor = "black";
        basemap = "gray-vector";
        break;
    }

    if (!map) return;

    map.basemap = (basemap as unknown) as Basemap;
    // Trigger a route redraw so it uses our new colors
    selectedRoute = selectedRoute;
  }

  onMount(async () => {
    // TODO: currently locked on version 4.14 because there's an issue in later versions where rotated text isn't properly aligned
    setDefaultOptions({ version: "4.14", css: true });

    const [Map, MapView, BasemapToggle] = await loadModules([
      "esri/Map",
      "esri/views/MapView",
      "esri/widgets/BasemapToggle",
    ]);

    map = new Map({ basemap });
    view = new MapView({ container: mapContainer, map, zoom: 2 });

    const basemapToggle = new BasemapToggle({ view, nextBasemap: "hybrid" });
    view?.ui.add(basemapToggle, "bottom-right");

    airportRunways = await AirportRunways.initAsync(map);
  });

  onDestroy(() => {
    if (view) view.container = null;
  });

  export async function viewAirport(airport: Airport) {
    if (!view) return;

    const [Point] = await loadModules(["esri/geometry/Point"]);

    const center = new Point({
      latitude: airport.position.latitudeDeg,
      longitude: airport.position.longitudeDeg,
    });

    view.goTo({ center, scale: airportRunways.layer.minScale / 2 || 100_000 });
  }

  async function drawRouteAndRunways(route: Route | undefined): Promise<void> {
    if (!view || drawingRoute) return;

    view.graphics.removeAll();
    airportRunways.clear();

    if (!route) return;

    drawingRoute = true;

    const result = Promise.all([
      drawRoute(route),
      airportRunways.draw(route.from, textColor),
      airportRunways.draw(route.to, textColor),
    ]);

    return result.then(() => {}).finally(() => (drawingRoute = false));
  }

  async function drawRoute(route: Route) {
    const [
      SimpleMarkerSymbol,
      SimpleLineSymbol,
      TextSymbol,
      Polyline,
      geometryEngine,
      Point,
      Graphic,
    ] = await loadModules([
      "esri/symbols/SimpleMarkerSymbol",
      "esri/symbols/SimpleLineSymbol",
      "esri/symbols/TextSymbol",
      "esri/geometry/Polyline",
      "esri/geometry/geometryEngine",
      "esri/geometry/Point",
      "esri/Graphic",
    ]);

    const pointFromArpt = (arpt: Airport): Point =>
      new Point({
        latitude: arpt.position.latitudeDeg,
        longitude: arpt.position.longitudeDeg,
      });

    const depPos = pointFromArpt(route.from);
    const arrPos = pointFromArpt(route.to);

    const linePath: Polyline = new Polyline({
      paths: [
        [depPos.x, depPos.y],
        [arrPos.x, arrPos.y],
      ],
    });

    const lineSymbol: SimpleLineSymbol = new SimpleLineSymbol({
      width: 2,
    });

    const geodesicLine: Polyline = geometryEngine.geodesicDensify(
      linePath,
      10_000
    );

    const symbol: SimpleMarkerSymbol = new SimpleMarkerSymbol({
      style: "diamond",
      size: "10px",
    });

    view.graphics.add(new Graphic(depPos, symbol));
    view.graphics.add(new Graphic(arrPos, symbol));
    view.graphics.add(new Graphic(geodesicLine, lineSymbol));

    let nameProps = {
      color: textColor,
      text: "DEP",
      yoffset: 7,
      font: { size: 8, family: "sans-serif" },
    };

    const depMarker: TextSymbol = new TextSymbol(nameProps);
    nameProps.text = "ARR";
    const arrMarker: TextSymbol = new TextSymbol(nameProps);

    view.graphics.add(new Graphic(depPos, depMarker));
    view.graphics.add(new Graphic(arrPos, arrMarker));
  }
</script>

<style>
  .route-map {
    display: flex;
    flex: 1 1 85%;
  }

  :global(.route-map .esri-view-surface::after) {
    outline: 0 !important;
  }

  .container.loaded {
    width: 100%;
    height: 100%;
  }
</style>

<div class="route-map">
  {#if !map}
    <Spinner />
  {/if}
  <div class="container" class:loaded={map} bind:this={mapContainer} />
</div>

// frontend/src/components/RouteMap.tsx
import * as React from 'react';
import { setDefaultOptions, loadModules } from 'esri-loader';
import type { Route, Airport } from '../types/route';
import './RouteMap.css';

interface Props {
    drawRoute?: Route,
}

interface State {
    isLoaded: boolean,
}

class RouteMap extends React.Component<Props, State> {
    state: State = {
        isLoaded: false,
    };

    private map: any;
    private mapRef: any = React.createRef();
    private view: any;
    private runwayLayer: any;

    componentDidMount() {
        setDefaultOptions({ css: true });

        loadModules([
            "esri/Map",
            "esri/views/MapView",
            "esri/widgets/BasemapToggle",
            "esri/layers/GraphicsLayer",
        ]).then(([
            Map,
            MapView,
            BasemapToggle,
            GraphicsLayer,
        ]) => {
            this.map = new Map({
                basemap: "gray-vector"
            });

            this.view = new MapView({
                container: this.mapRef.current,
                map: this.map,
                zoom: 2
            });

            const basemapToggle = new BasemapToggle({
                view: this.view,
                nextBasemap: "hybrid"
            });

            this.runwayLayer = new GraphicsLayer({
                minScale: 200_000
            });

            this.map.add(this.runwayLayer);
            this.view.ui.add(basemapToggle, "bottom-right");

            this.setState({ isLoaded: true });
        }).catch(err => console.error(err));
    }

    componentWillUnmount() {
        if (this.view)
            this.view.container = null;
    }

    componentDidUpdate() {
        if (!this.props.drawRoute || !this.state.isLoaded)
            return;

        this.drawCurrentRoute();
        this.drawRouteRunways(this.props.drawRoute!);
    }

    private drawCurrentRoute = () => loadModules([
        "esri/symbols/SimpleMarkerSymbol",
        "esri/symbols/SimpleLineSymbol",
        "esri/geometry/Polyline",
        "esri/geometry/geometryEngine",
        "esri/geometry/Point",
        "esri/Graphic",
    ]).then(([
        SimpleMarkerSymbol,
        SimpleLineSymbol,
        Polyline,
        geometryEngine,
        Point,
        Graphic
    ]) => {
        this.view?.graphics.removeAll();

        if (!this.props.drawRoute)
            return;

        const route = this.props.drawRoute!;

        const marker = new SimpleMarkerSymbol({
            style: "diamond",
            size: "10px"
        });

        const pointFromAirport = (airport: Airport) => new Point({
            latitude: airport.position.latitudeDeg,
            longitude: airport.position.longitudeDeg,
        });

        const depPos = pointFromAirport(route.from);
        const arrPos = pointFromAirport(route.to);

        const linePath = new Polyline({
            paths: [[depPos.x, depPos.y], [arrPos.x, arrPos.y]]
        });

        const lineSymbol = new SimpleLineSymbol({
            width: 2
        });

        const geodesicLine = geometryEngine.geodesicDensify(linePath, 10_000);

        this.view.graphics.add(new Graphic(depPos, marker));
        this.view.graphics.add(new Graphic(arrPos, marker));
        this.view.graphics.add(new Graphic(geodesicLine, lineSymbol));
    }).catch(err => console.error(err));

    private drawRouteRunways(route: Route): void {
        this.runwayLayer?.graphics.removeAll();
        this.drawAirportRunways(route.from);
        this.drawAirportRunways(route.to);
    }

    private drawAirportRunways(airport: Airport): void {
        if (airport.runways.length === 0)
            return;

        loadModules([
            "esri/symbols/SimpleLineSymbol",
            "esri/geometry/Point",
            "esri/geometry/Polyline",
            "esri/symbols/TextSymbol",
            "esri/Graphic",
        ]).then(([SimpleLineSymbol, Point, Polyline, TextSymbol, Graphic]) => {
            const runwaySymbol = new SimpleLineSymbol({
                width: 3
            });

            for (const runway of airport.runways) {
                if (!runway.heMarker || !runway.leMarker)
                    continue;

                const hePos = new Point({
                    x: runway.heMarker!.position.longitudeDeg,
                    y: runway.heMarker!.position.latitudeDeg,
                });

                const lePos = new Point({
                    x: runway.leMarker!.position.longitudeDeg,
                    y: runway.leMarker!.position.latitudeDeg,
                });

                const runwayLine = new Polyline({
                    paths: [[hePos.x, hePos.y], [lePos.x, lePos.y]]
                });

                this.runwayLayer.graphics.add(new Graphic(runwayLine, runwaySymbol));

                let nameProperties = {
                    color: "black",
                    text: runway.heMarker!.name,
                    angle: angleFromPoints(hePos, lePos),
                    yoffset: -10,
                    font: {
                        size: 8,
                        family: "sans-serif"
                    }
                };

                const heText = new TextSymbol(nameProperties);
                this.runwayLayer.graphics.add(new Graphic(hePos, heText));

                nameProperties.text = runway.leMarker!.name;
                nameProperties.angle += 180;
                const southText = new TextSymbol(nameProperties);

                this.runwayLayer.graphics.add(new Graphic(lePos, southText));
            }
        }).catch(err => console.error(err));
    }

    viewAirport = (airport: Airport) => loadModules([
        "esri/geometry/Point"
    ]).then(([
        Point
    ]) => {
        const center = new Point({
            latitude: airport.position.latitudeDeg,
            longitude: airport.position.longitudeDeg,
        });

        this.view?.goTo({
            center,
            scale: this.runwayLayer?.minScale / 2,
        });
    }).catch(err => console.error(err));

    render() {
        return (
            <div className="route-map">
                {!this.state.isLoaded && <h2 id="loading-text">Loading map</h2>}
                <div id="route-map-container" ref={this.mapRef}></div>
            </div>
        );
    }
}

interface Point {
    x: number,
    y: number,
}

// https://stackoverflow.com/a/18738281
function angleFromPoints(start: Point, end: Point): number {
    const startRad: Point = {
        x: toRad(start.x),
        y: toRad(start.y)
    };

    const endRad: Point = {
        x: toRad(end.x),
        y: toRad(end.y),
    };

    const deltaLon = endRad.x - startRad.x;

    const y = Math.sin(deltaLon) * Math.cos(endRad.y);
    const x = Math.cos(startRad.y) * Math.sin(endRad.y) - Math.sin(startRad.y)
        * Math.cos(endRad.y) * Math.cos(deltaLon);

    return (toDeg(Math.atan2(y, x)) + 360) % 360;
}

function toRad(ang: number): number {
    return ang * (Math.PI / 180);
}

function toDeg(ang: number): number {
    return ang * (180 / Math.PI);
}

export default RouteMap;
