// frontend/src/components/RouteInfo/FilterForm/AirportFilters/index.svelte
<script lang="ts">
  import Box from "../../Box.svelte";
  import type { AirportFiltersInput } from "../types";
  import AirportType from "./AirportType.svelte";
  import IcaoInput from "./ICAOInput.svelte";
  import LengthInput from "./LengthInput.svelte";
  import CountriesInput from "./CountriesInput.svelte";

  export let name: string;

  export let state: AirportFiltersInput = {
    icao: "",
    type: "unknown",
    length: "",
    countries: "",
  };
</script>

<Box {name}>
  <IcaoInput bind:value={state.icao} />
  <AirportType bind:value={state.type} />
  <LengthInput bind:value={state.length} />
  <CountriesInput bind:value={state.countries} />
</Box>

// frontend/src/components/RouteInfo/FilterForm/AirportFilters/AirportFilters.tsx
import * as React from 'react';
import Box from '../Box';
import ICAOInput from './ICAOInput';
import AirportTypeInput, { AirportType } from './AirportTypeInput';
import RunwayLengthInput, { RunwayLength } from './RunwayLengthInput';
import CountriesInput from './CountriesInput';
import './AirportFilters.css';

interface Props {
    label: string,
    className?: string,
    onChange?: (newState: State) => void,
}

export interface State {
    icao: string,
    airportType: AirportType,
    runwayLength?: RunwayLength,
    countries: string[],
}

class AirportFilters extends React.Component<Props, State> {
    state: State = {
        icao: "",
        airportType: "unknown",
        countries: [],
    };

    private update<T extends keyof State>(newState: Pick<State, T>) {
        this.setState(newState, () => this.props.onChange?.(this.state));
    }

    render() {
        return (
            <Box className={`filter-box ${this.props.className}`} label={this.props.label}>
                <ICAOInput value={this.state.icao} onChange={icao => this.update({ icao })} />
                <AirportTypeInput selected={this.state.airportType} onChange={airportType => this.update({ airportType })} />
                <RunwayLengthInput onChange={runwayLength => this.update({ runwayLength })} />
                <CountriesInput onChange={countries => this.update({ countries })} />
            </Box>
        );
    }
}

export default AirportFilters;
