// frontend/src/components/FilterForm/AirportFilters/AirportFilters.tsx
import * as React from 'react';
import Box from '../Box';
import ICAOInput from './ICAOInput';
import AirportTypeInput, { AirportType } from './AirportTypeInput';
import RunwayLengthInput, { RunwayLength } from './RunwayLengthInput';
import CountriesInput from './CountriesInput';
import './AirportFilters.css';

interface Props {
    label: string,
    className?: string,
    onChange?: (newState: State) => void,
}

export interface State {
    icao: string,
    airportType: AirportType,
    runwayLength?: RunwayLength,
    countries: string[],
}

class AirportFilters extends React.Component<Props, State> {
    state: State = {
        icao: "",
        airportType: "none",
        countries: [],
    };

    private update<T extends keyof State>(newState: Pick<State, T>) {
        this.setState(newState, () => this.props.onChange?.(this.state));
    }

    render() {
        return (
            <Box className={`filter-box ${this.props.className}`} label={this.props.label}>
                <ICAOInput value={this.state.icao} onChange={icao => this.update({ icao })} />
                <AirportTypeInput selected={this.state.airportType} onChange={airportType => this.update({ airportType })} />
                <RunwayLengthInput onChange={runwayLength => this.update({ runwayLength })} />
                <CountriesInput onChange={countries => this.update({ countries })} />
            </Box>
        );
    }
}

export default AirportFilters;

// frontend/src/components/RouteInfo/FilterForm/AirportFilters/AirportFilters.vue
<template>
  <box class="airport-filters" :label="label">
    <icao-input @input="set('icao', $event)" @has-error="setErrorAndPropagate('icao', $event)" />
    <airport-type-input @change="set('airportType', $event)" />
    <runway-length-input
      @input="set('runwayLength', $event)"
      @has-error="setErrorAndPropagate('runwayLength', $event)"
    />
    <countries-input @input="set('countries', $event)" />
  </box>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";
import {
  VueWithErrorCatcher,
  ErrorState
} from "../../../../util/vue_with_error";
import Box from "../Box.vue";
import IcaoInput from "./IcaoInput.vue";
import AirportTypeInput from "./AirportTypeInput.vue";
import RunwayLengthInput, {
  Serialized as RunwayLength
} from "./RunwayLengthInput.vue";
import CountriesInput from "./CountriesInput.vue";

export interface State {
  icao?: string;
  airportType?: string;
  runwayLength?: RunwayLength;
  countries?: string[];
}

interface ErrorStates extends ErrorState {
  icao: boolean;
  runwayLength: boolean;
}

@Component({
  components: {
    Box,
    IcaoInput,
    AirportTypeInput,
    RunwayLengthInput,
    CountriesInput
  }
})
export default class AirportFilters extends VueWithErrorCatcher<ErrorStates> {
  @Prop({ required: true }) label!: string;

  private state: State = {};

  constructor() {
    super({
      icao: false,
      runwayLength: false
    });
  }

  private set<T extends keyof State>(field: T, value: any) {
    this.state[field] = value;
    this.$emit("changed", this.state);
  }
}
</script>
