// frontend/src/components/RouteInfo/FilterForm/AirportFilters/CountriesInput.vue
<template>
  <form-input label="Countries" class="countries-input" @input="input" />
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import FormInput from "../FormInput.vue";

@Component({ components: { FormInput } })
export default class CountriesInput extends Vue {
  private input(value: string) {
    const countries = value.split(",").reduce((acc, value) => {
      const trimmed = value.trim();
      if (trimmed.length > 0) acc.push(trimmed);
      return acc;
    }, [] as string[]);

    const inputValue = countries.length > 0 ? countries : undefined;
    this.$emit("input", inputValue);
  }
}
</script>

<style scoped>
.countries-input >>> input {
  width: 7vmax;
}
</style>

// frontend/src/components/RouteInfo/FilterForm/AirportFilters/CountriesInput.tsx
import * as React from 'react';
import Input, { InputChangeEvent } from '../Input';

interface Props {
    onChange?: (selectedCountries: string[]) => void,
}

interface State {
    value: string,
}

class CountriesInput extends React.Component<Props, State> {
    state: State = {
        value: "",
    };

    private onChange = (event: InputChangeEvent) => {
        const value = event.target.value;
        this.setState({ value });

        if (!this.props.onChange)
            return;

        const selected = value
            .split(',')
            .reduce((acc, value) => {
                const trimmed = value.trim();

                if (trimmed.length > 0)
                    acc.push(trimmed);

                return acc;
            }, [] as string[]);

        this.props.onChange!(selected);
    }

    render() {
        return (
            <Input
                label="Countries"
                inputClasses="countries-input"
                value={this.state.value}
                onChange={this.onChange}
            />
        );
    }
}

export default CountriesInput;
