// frontend/src/components/Tabs/index.svelte
<script lang="ts" context="module">
  export const tabsContext = {};
</script>

<script lang="ts">
  import { setContext, onMount } from "svelte";
  import { writable } from "svelte/store";

  export let headers: string[] = [];

  let tabs: number[] = [];
  const selected: any = writable(null);

  setContext(tabsContext, {
    selected,
    registerTab(id: number) {
      tabs = [...tabs, id];
    },
  });

  function changeTab(index: number) {
    $selected = tabs[index];
  }

  onMount(() => {
    changeTab(0);
  });
</script>

<style>
  .tabs {
    display: flex;
    flex-direction: column;
    flex: 1 1 0;
  }

  .tab-headers {
    display: flex;
    justify-content: space-evenly;
    flex-wrap: nowrap;
    overflow: hidden;
    list-style: none;
    padding: 0;
    margin: 0 0 1em;
    font-size: 1em;
    cursor: pointer;
    background-color: var(--tab-color);
  }

  .tab-header {
    display: flex;
    padding: 0.75em 0.5em;
    width: 100%;
    justify-content: center;
  }

  .tab-header:hover {
    background-color: var(--hover-color);
  }

  .tab-header.selected {
    background-color: var(--bg-color);
  }

  .tab-header:not(.selected) {
    border-bottom: 1px solid var(--border-color);
  }

  .tab-header:not(:last-child) {
    border-right: 1px solid var(--border-color);
  }
</style>

<div class="tabs">
  <ul class="tab-headers">
    {#each headers as header, idx}
      <li
        class="tab-header"
        class:selected={tabs[idx] === $selected}
        on:click={() => changeTab(idx)}>
        {header}
      </li>
    {/each}
  </ul>
  <slot />
</div>

// frontend/src/components/RouteInfo/Tabs/Tabs.vue
<template>
  <div class="tabs">
    <ul class="tab-list">
      <li
        v-for="tab in tabs"
        :key="tab.name"
        :class="{ 'selected-tab': tab.isSelected }"
        class="tab-header uppercase"
        @click="selectTab(tab)"
      >
        {{ tab.name }}
      </li>
    </ul>
    <slot />
  </div>
</template>

<script lang="ts">
import { Component } from "vue-property-decorator";
import Vue from "vue";
import Tab from "./Tab.vue";

@Component
export default class Tabs extends Vue {
  private tabs: Tab[] = [];
  private lastTab: Tab | null = null;

  mounted() {
    this.tabs = this.$children as Tab[];
    this.lastTab = this.tabs.find((tab) => tab.isSelected) || null;
  }

  selectTab(tab: Tab) {
    if (this.lastTab) this.lastTab.isSelected = false;

    tab.isSelected = true;
    this.lastTab = tab;
  }
}
</script>

<style scoped>
.tab-list {
  display: flex;
  justify-content: space-evenly;
  flex-wrap: nowrap;
  overflow: hidden;
  padding: 0;
  margin: 0;
  list-style: none;
  background-color: var(--tab-color);
  text-align: center;
}

.tab-header {
  cursor: default;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  font-size: 1vw;
  padding: 0.5vw;
  border-bottom: 1px solid var(--border-color);
}

.tab-header:not(.selected-tab) {
  transition: background-color 200ms ease-in-out;
}

.tab-header:hover {
  background-color: var(--hover-color);
}

.tab-header:not(:last-child) {
  border-right: 1px solid var(--border-color);
}

.tab-header.selected-tab {
  background-color: var(--bg-color);
  border-bottom: 0;
}

.tab-content {
  padding-top: 10px;
}
</style>
