// frontend/src/components/RouteInfo/FilterForm/AirportFilters/AirportTypeInput.vue
<template>
  <div>
    <label>Type</label>
    <select class="airport-type-select" @change="changed" v-bind="$attrs">
      <option selected value="unknown"></option>
      <option value="large_airport">Large</option>
      <option value="medium_airport">Medium</option>
      <option value="small_airport">Small</option>
      <option value="closed">Closed</option>
      <option value="heliport">Heliport</option>
      <option value="seaplane_base">Seaplane Base</option>
    </select>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";

@Component({ inheritAttrs: false })
export default class AirportTypeInput extends Vue {
  private changed(event: any) {
    const value: string | undefined = event?.target?.value;
    this.$emit("change", value !== "unknown" ? value : undefined);
  }
}
</script>

<style scoped>
.airport-type-select {
  width: 10vh;
}
</style>

// frontend/src/components/FilterForm/AirportFilters/AirportTypeInput.tsx
import * as React from 'react';

interface AirportTypes {
    none: string,
    large: string,
    medium: string,
    small: string,
}

export type AirportType = keyof AirportTypes;

interface Props {
    selected: AirportType,
    onChange?: (selected: AirportType) => void,
}

class AirportTypeInput extends React.Component<Props> {
    static readonly typeNames: AirportTypes = {
        none: "",
        large: "Large",
        medium: "Medium",
        small: "Small",
    };

    static readonly types = Object.keys(AirportTypeInput.typeNames).map(type => {
        const display = (AirportTypeInput.typeNames as any)[type];

        return (
            <option key={type} value={type}>{display}</option>
        );
    });

    private onChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
        const type = event.target.value as AirportType;
        this.props.onChange?.(type);
    }

    render() {
        return (
            <React.Fragment>
                <label>Type</label>
                <select className="airport-type-input" value={this.props.selected} onChange={this.onChange}>
                    {AirportTypeInput.types}
                </select>
            </React.Fragment>
        );
    }
}

export default AirportTypeInput;
