// frontend/src/components/RouteInfo/FilterForm/AirportFilters/ICAOInput.svelte
<script lang="ts">
  import Input from "../Input.svelte";

  export let value: string;

  function onInput(event: any) {
    value = event.target.value.toUpperCase();
  }
</script>

<style>
  :global(.icao-input) {
    width: 2em;
  }
</style>

<Input
  inputClass="icao-input"
  name="icao"
  label="ICAO"
  maxLength={4}
  on:input={onInput}
  {value} />

// frontend/src/components/FilterForm/AirportFilters/ICAOInput.tsx
import * as React from 'react';
import Input, { InputChangeEvent } from '../Input';

interface State {
    value: string,
}

class ICAOInput extends React.Component<{}, State> {
    state = {
        value: "",
    };

    private static isValid(icao: string): boolean {
        return icao.allChars((ch) => ch.isDigit() || ch.isAlphanumericUpper());
    }

    private onChange = (event: InputChangeEvent) => {
        const icao = event.target.value.toUpperCase();

        if (!ICAOInput.isValid(icao)) {
            event.preventDefault();
            return;
        }

        this.setState({
            value: icao,
        });
    }

    render() {
        return (
            <Input
                label="ICAO"
                inputClasses="icao-input"
                maxLength={4}
                value={this.state.value}
                onChange={this.onChange}
            />
        );
    }
}

export default ICAOInput;
