// frontend/src/components/RouteInfo/RouteViewer/index.svelte
<script lang="ts">
  import type { Route } from "../types";
  import Spinner from "../../Spinner.svelte";
  import RouteTable from "./RouteTable.svelte";

  export let routes: Route[];
  export let loading: boolean;
  export let firstRender: boolean;
</script>

<style>
  .route-viewer.hidden {
    max-height: 0;
  }

  .route-viewer:not(.hidden) {
    border-bottom: 1px solid var(--border-color);
  }

  .route-viewer {
    display: flex;
    flex-direction: column;
    flex: 1 0 40%;
    max-height: 40%;
    transition: max-height 0.3s ease-in-out;
    overflow: hidden auto;
  }

  .route-viewer .container {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .no-routes-text {
    justify-content: center;
    align-self: center;
    font-size: 1.5em;
  }
</style>

<div class="route-viewer scrollbar" class:hidden={firstRender}>
  {#if loading || routes.length === 0}
    <RouteTable />
    <div class="container">
      {#if loading}
        <Spinner />
      {:else}
        <span class="no-routes-text">NO ROUTES FOUND</span>
      {/if}
    </div>
  {:else}
    <RouteTable {routes} />
  {/if}
</div>

// frontend/src/components/RouteInfo/RouteViewer/RouteViewer.vue
<template>
  <div class="route-table-wrapper">
    <route-table-body v-if="loading">
      <span class="uppercase">Loading</span>
    </route-table-body>
    <route-table-body v-else-if="routes.length === 0">
      <span class="uppercase">No routes found</span>
    </route-table-body>
    <route-table v-else :routes="routes" />
  </div>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";
import Vue from "vue";
import RouteTable from "./RouteTable.vue";
import RouteTableBody from "./RouteTableBody.vue";
import Route from "../../../types/route";

@Component({ components: { RouteTable, RouteTableBody } })
export default class RouteViewer extends Vue {
  @Prop({ default: true }) private loading!: boolean;
  @Prop({ default: () => [] }) private routes!: Route[];
}
</script>

<style>
:root {
  --route-table-height: 40%;
}
</style>

<style scoped>
.route-table-wrapper {
  width: 100%;
  height: var(--route-table-height);
  overflow: hidden;
  border-bottom: 2px solid var(--border-color);
}
</style>
