// frontend/src/components/MainPanel/RouteInfo/Box.svelte
<script lang="ts">
  export let name: string;
  export let className: string = "";
</script>

<style>
  .box {
    display: flex;
    flex-direction: column;
    font-size: 1.1em;
  }

  span {
    text-align: center;
    margin-bottom: 0.5em;
    font-size: 1.25em;
  }

  .box-content {
    display: grid;
    row-gap: 1em;
    overflow: hidden;
    border: 1px solid var(--border-color);
    padding: 1em 0.75em;
  }

  :global(.box-content label) {
    grid-column: 1 / 2;
    padding-right: 0.5em;
    align-self: center;
  }

  :global(.box-content input, .box-content select) {
    grid-column: 2 / 3;
    max-width: 5em;
  }
</style>

<div class={`box ${className}`}>
  <span>{name}</span>
  <div class="box-content">
    <slot />
  </div>
</div>

// frontend/src/components/RouteInfo/FilterForm/Box.vue
<template>
  <div class="box">
    <label>{{ label }}</label>
    <div class="box-content">
      <slot />
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";

@Component
export default class Box extends Vue {
  @Prop({ required: true }) label!: string;
}
</script>

<style scoped>
.box {
  width: 15vw;
  align-self: center;
}

.box > label {
  text-align: center;
  display: block;
  padding-top: 25px;
  padding-bottom: 5px;
  font-size: 2.5vh;
}

.box-content {
  display: grid;
  row-gap: 10px;
  overflow: hidden;
  border: 1px solid var(--border-color);
  padding: 1.5vh;
}

.box-content >>> label {
  font-size: 2.25vh;
  padding-right: 15px;
}

.box-content >>> input,
select {
  font-size: 2.25vh;
}
</style>
