// frontend/src/components/MainPanel/RouteInfo/FilterForm/index.svelte
<script lang="ts">
  import SpeedInput from "./SpeedInput.svelte";
  import AirportFilters from "./AirportFilters/index.svelte";
  import type { FindRoutesQuery } from "../types";
  import { createEventDispatcher } from "svelte";
  import ErrorMessage from "./ErrorMessage.svelte";
  import TimeDist from "./TimeDist/index.svelte";

  export let error: string | null = null;
  export let loadingRoutes: boolean;

  let speedRef: any = null;
  let departureRef: any = null;
  let arrivalRef: any = null;
  let timeDistRef: any = null;

  const dispatch = createEventDispatcher();

  function filtersSubmitted() {
    const speed = speedRef?.parse();
    if (!speed) return;

    const query: FindRoutesQuery = {
      speed,
      departure: departureRef?.parse() || undefined,
      arrival: arrivalRef?.parse() || undefined,
      timeDist: timeDistRef?.parse() || undefined,
    };

    dispatch("findroutes", query);
  }
</script>

<style>
  .filter-form {
    margin-top: 1em;
    display: flex;
    flex-direction: column;
    flex-wrap: nowrap;
    padding: 0 1em;
    align-items: center;
  }

  .find-routes-btn {
    margin-bottom: 1em;
    padding: 0.25em;
    font-size: 1.5em;
    width: 60%;
    align-self: center;
  }

  .find-routes-btn:disabled {
    color: var(--disabled-text-color);
    background-color: var(--disabled-color);
  }

  :global(.filter-form .box:not(:first-child)) {
    margin-top: 1em;
  }

  :global(.filter-form > label) {
    font-size: 1.3em;
  }
</style>

{#if error}
  <ErrorMessage {error} />
{/if}

<form class="filter-form" on:submit|preventDefault={filtersSubmitted}>
  <SpeedInput bind:this={speedRef} />
  <AirportFilters name="Departure" bind:this={departureRef} />
  <AirportFilters name="Arrival" bind:this={arrivalRef} />
  <TimeDist bind:this={timeDistRef} />
  <input
    type="submit"
    class="find-routes-btn"
    value={loadingRoutes ? 'Searching..' : 'Find Routes'}
    disabled={loadingRoutes} />
</form>

// frontend/src/components/RouteInfo/FilterForm/FilterForm.vue
<template>
  <form v-on:submit.prevent="onSubmitted" class="filter-form">
    <speed-input name="speed" @error="hasError = $event" />
    <input type="submit" class="find-routes-btn" value="Find Routes" :disabled="hasError" />
  </form>
</template>

<script lang="ts">
import { Component } from "vue-property-decorator";
import Vue from "vue";
import SpeedInput, { Speed } from "./SpeedInput.vue";

export interface State {
  speed: Speed;
  departure?: any;
  arrival?: any;
  timeDist?: any;
}

@Component({ components: { SpeedInput } })
export default class FilterForm extends Vue {
  private hasError = false;

  private onSubmitted(event: any) {
    const target = event.target;

    const state: State = {
      speed: Speed.parse(target.speed.value)
    };

    this.$emit("submitted", state);
  }
}
</script>

<style scoped>
.filter-form {
  display: flex;
  flex-direction: column;
  flex-wrap: nowrap;
  padding: 15px;
}

.speed-input {
  align-self: center;
}

.find-routes-btn {
  margin-top: 3vh;
  width: 60%;
  align-self: center;
  font-size: 3vh;
  padding: 5px;
}
</style>
